spring:
  profiles:
    active: dev
---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: infodba
      password: infodba
      url: jdbc:sqlserver://localhost:1433;databaseName=tc
  jpa:
    show-sql: true
---
spring:
  profiles: dev
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
     format_sql: true
     dialect : org.hibernate.dialect.SQLServerDialect
logging.level:
  org.hibernate.SQL: debug

